export const USERS_DATA = [
  {
    "_id": "58de1fc7a9fa77ea02afcfac",
    "index": 0,
    "isActive": false,
    "age": 39,
    "title": "Dr.",
    "name": "Edna",
    "surname": "Burris",
    "gender": "female",
    "company": "VIOCULAR",
    "country": "Albania",
    "registered": "29-13-2017"
  },
  {
    "_id": "58de1fc789e2796a20817541",
    "index": 1,
    "isActive": false,
    "age": 34,
    "title": "Mrs.",
    "name": "Rivers",
    "surname": "Solis",
    "gender": "male",
    "company": "ZOGAK",
    "country": "United Arab Emirates",
    "registered": "26-53-2014"
  },
  {
    "_id": "58de1fc799eb84afbcd4b368",
    "index": 2,
    "isActive": true,
    "age": 28,
    "title": "Mrs.",
    "name": "Dillon",
    "surname": "Cantu",
    "gender": "male",
    "company": "BRAINQUIL",
    "country": "China",
    "registered": "29-38-2016"
  },
  {
    "_id": "58de1fc77447cbe9fa558b3a",
    "index": 3,
    "isActive": true,
    "age": 24,
    "title": "Dr.",
    "name": "Leon",
    "surname": "Daniels",
    "gender": "male",
    "company": "HONOTRON",
    "country": "Lao",
    "registered": "28-53-2016"
  },
  {
    "_id": "58de1fc7f4e078249f8ceadf",
    "index": 4,
    "isActive": false,
    "age": 37,
    "title": "Mr.",
    "name": "Bethany",
    "surname": "Melendez",
    "gender": "female",
    "company": "TERAPRENE",
    "country": "Iraq",
    "registered": "08-26-2015"
  },
  {
    "_id": "58de1fc77080acc1f2af6221",
    "index": 5,
    "isActive": false,
    "age": 20,
    "title": "Mr.",
    "name": "Henry",
    "surname": "Raymond",
    "gender": "male",
    "company": "ISOLOGICA",
    "country": "United Arab Emirates",
    "registered": "11-50-2015"
  },
  {
    "_id": "58de1fc7bacbe91cefc67fca",
    "index": 6,
    "isActive": false,
    "age": 33,
    "title": "Ms.",
    "name": "Lina",
    "surname": "Hebert",
    "gender": "female",
    "company": "SUNCLIPSE",
    "country": "Panama",
    "registered": "07-50-2016"
  },
  {
    "_id": "58de1fc7d6cee6888c75b531",
    "index": 7,
    "isActive": false,
    "age": 31,
    "title": "Ms.",
    "name": "Tisha",
    "surname": "Lucas",
    "gender": "female",
    "company": "GONKLE",
    "country": "Iraq",
    "registered": "17-03-2015"
  },
  {
    "_id": "58de1fc7aa6d889df0319234",
    "index": 8,
    "isActive": true,
    "age": 20,
    "title": "Mrs.",
    "name": "Esmeralda",
    "surname": "Barnes",
    "gender": "female",
    "company": "PHOLIO",
    "country": "Lao",
    "registered": "20-35-2015"
  }
]
